name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: echo "::error::Error message"
      - name: Debug
        run: echo "::debug::Debug message"
      - name: Notice
        run: echo "::notice::Notice message"



  
